NIAEFEUP/tts-fe

docker-compose.yaml, dockerfile
Created configurations for development in docker.
=> Dockerfile and docker compose

src/AppTheme.js, src/components/CardFeature.jsx, src/components/Common/ChipBadge.jsx, src/components/FeupExchange/ChangeScheduleForm.jsx, src/components/FeupExchange/ScheduleBoxFormat.jsx, src/components/FeupExchange/SelectClassOption.jsx, src/components/FeupExchange/SelectClassOptions.jsx, src/components/FeupExchange/SelectCourses.jsx, src/components/Home/GridSection.jsx, src/components/Home/Hero.jsx, src/components/Layout/Footer.jsx, src/components/Layout/Header.jsx, src/components/Profile/OptionRow.jsx, src/components/Profile/ProfileCard.jsx, src/styles/ChangeScheduleForm.js, src/utils/index.js
=> New option show order

src/components/TimeTableScheduler/ChooseCoursesModal.jsx, src/pages/TimeTablePage.jsx, src/styles/TimeTable.js, src/utils/index.js
=> Add first sketch of "add extra ucs" feature

src/components/planner/SelectionModal.tsx
Following the update on #68, the credits banner has been hidden with comments.
=> Hide credits banner

src/App.tsx, src/api/backend.ts, src/components/layout/Header.tsx, src/components/planner/SelectionModal.tsx, src/config/default.json, src/utils/index.ts
Added config file for paths.
close #93
=> Config file for path

src/api/backend.ts, src/config/default.json
The backend has changed, thus it is also necessary to change the API requests.
=> Added year to the API 

src/utils/index.ts
=> Professors without weekday - wrong range

src/@types/index.d.ts, src/components/planner/Schedule.tsx, src/components/planner/ScheduleListbox.tsx
=> Practical lesson are represented as array

package-lock.json, package.json, src/components/layout/Footer.tsx, src/components/planner/ScheduleListbox.tsx, src/config/local.json, src/config/prod.json
- fixed professor dropdown, where the professors wouldn't be selected as they should
=> Fix professor dropdown

package-lock.json, package.json, src/@types/index.d.ts, src/components/planner/ShareButtons.tsx
=> Refactor schedule link

src/@types/index.d.ts, src/components/planner/CreditsBanner.tsx, src/components/planner/SelectionModal.tsx
=> Re-enable credits banner

src/App.tsx, src/api/backend.ts, src/pages/TimeTableScheduler.tsx
The previous location of the request to the Info endpoint was not correct as well as the actual endpoint.
=> Fixed info request location

src/api/backend.ts
=> Fixed endpoint path

src/@types/new_index.d.ts, src/components/planner/Sidebar.tsx, src/components/planner/sidebar/SessionController.tsx, src/components/planner/sidebar/sessionController/CsvExport.tsx, src/components/planner/sidebar/sessionController/Export.tsx, src/utils/index.ts
Closes #216 
This PR fixes the export to CSV. ~It just faces one problem: the schedule options are currently stored in the index after the correct one, making the export shift the schedules.~
=> Refactor export with new multiple options structure

src/components/planner/sidebar/CoursesController/ClassSelector.tsx
Now, when some of the teachers of the class is selected, it will be a possible option to show in the dropdown
=> Fix Classes Options and Selected teachers

src/api/backend.ts, src/components/planner/Schedule.tsx, src/components/planner/sidebar/CoursesController/ClassSelector.tsx, src/components/planner/sidebar/sessionController/CoursePicker.tsx, src/components/planner/sidebar/sessionController/course-picker/CourseYearCheckboxes.tsx, src/components/planner/sidebar/sessionController/course-picker/CourseYearTabs.tsx, src/pages/TimeTableScheduler.tsx
There were race conditions when the `classes` on the `picked courses` were updated with data from the backend
=> Solve race conditions from class fething on picked courses

package-lock.json, package.json, src/components/faqs/HeaderFaqs.tsx, src/components/faqs/PlannerFaqs.tsx, src/components/home/HeroPlanner.tsx, src/components/planner/schedule/PrintSchedule.tsx, src/components/planner/schedule/ToggleScheduleGrid.tsx, src/pages/About.tsx, src/pages/Faqs.tsx, src/utils/index.ts
Update the faqs and create new ones.
Also fix the screenshot and toogle grid buttons on dark mode
=> Fix faqs and dark theme buttons

src/App.tsx, src/api/backend.ts, src/api/storage.ts, src/components/planner/Sidebar.tsx, src/components/planner/schedules/LessonPopover.tsx, src/components/planner/sidebar/CoursesController.tsx, src/components/planner/sidebar/CoursesController/ClassSelector.tsx, src/components/planner/sidebar/OptionsController.tsx, src/components/planner/sidebar/SelectedOptionController.tsx, src/components/planner/sidebar/sessionController/CoursePicker.tsx, src/components/planner/sidebar/sessionController/course-picker/ClearAllCoursesButton.tsx, src/components/planner/sidebar/sessionController/course-picker/CourseYearCheckboxes.tsx, src/components/planner/sidebar/sessionController/course-picker/CourseYearTabs.tsx, src/components/planner/sidebar/sessionController/course-picker/Ects.tsx, src/components/planner/sidebar/sessionController/course-picker/PickedCourse.tsx, src/components/planner/sidebar/sessionController/course-picker/PickedCoursesList.tsx, src/components/ui/button.tsx, src/components/ui/tabs.tsx, src/contexts/CourseContext.tsx, src/pages/TimeTableScheduler.tsx, src/utils/index.ts
Closes #237 
- Sort course units by higher etcs to lower in the modal search
- Modal UI improvements
- Others UI improvements
- Fix bug of localstorage classes
- Adds a redirect on / to /tts/planner
New UIs:
=> UI improvements, fix bug and add redirect on /

src/components/planner/Schedule.tsx, src/components/planner/sidebar/sessionController/CoursePicker.tsx, src/components/planner/sidebar/sessionController/course-picker/CourseYearCheckboxes.tsx, src/components/planner/sidebar/sessionController/course-picker/Ects.tsx, src/components/planner/sidebar/sessionController/course-picker/MajorSearchCombobox.tsx, src/components/planner/sidebar/sessionController/course-picker/PickedCoursesList.tsx
=> fix: course picker is responsive on smaller devices

src/@types/index.d.ts, src/components/planner/schedules/LessonBox.tsx, src/components/planner/sidebar/CoursesController/ClassItem.tsx, src/utils/index.ts
The conflicts with laboratorial classes were being treated as with theorical classes. In the case of "TP" with "PL" classes, the warning would appear as yellow instead of red. This PR solves this problem.
=> Fix conflicts with laboratorial classes

src/components/planner/sidebar/sessionController/course-picker/MajorSearchCombobox.tsx
=> fix: major results are scrollable

src/components/planner/sidebar/CoursesController/ClassSelectorDropdownController.tsx
Closes #286 and #288 
Besides fixing the problem when there are classes in an uc but those are not shown on the dropdown, below are the ways that we show to the user that there are no professors or options.
=> fix: sometimes class options were not always shown

src/components/planner/sidebar/selectedOptionController/RandomFill.tsx
=> feat: random fill warns if no valid schedule found and if no classes found

src/components/planner/sidebar/CoursesController/ClassItem.tsx, src/components/planner/sidebar/sessionController/Refresh.tsx, src/utils/index.ts
The solution I implemented was to create a Record of oldID to newID and then using that record to modify the multiple options. The record is made using the prev picked courses and the new ones(finalCourses) and comparing them by name, picked courses has oldID- Name , final courses has newID-Name so both give us oldID-newID as name is unique (I think), then we go over the multiple options and update it with the equivalent of the new id lets say that the picked id is 1 and the record has 1-7 then we update to 7 if the record has 1-null we update it to null
=> fix : now picked class id is updated

src/components/planner/sidebar/selectedOptionController/RandomFill.tsx
There was a previous PR (#293) to the frontend that changed things in random fill and messed up it being scrollable.
This pr fixes that.
=> fix: random fill scroll

README.md, index.html, public/manifest.json, src/App.tsx, src/components/layout/index.tsx, src/pages/TimeTableSelector.tsx, src/pages/index.ts
=> chore: change default app title from timetablescheduler to timetableselector

src/components/exchange/schedule/ExchangeSchedule.tsx
Now both classes T and TP/PL in exchange schedule have value of the pratical class if it exists else the other
=> fix : now both classes have value of pratical one

src/components/exchange/requests/issue/cards/CreateRequestCard.tsx
- Fixed issuerOriginClass update bug, where the student's original class was being updated based on the choice of exchange class
- Implemented Preview for exchange class options on hover.
https://github.com/user-attachments/assets/d844b44a-f20b-4576-abc9-c91073b7bbaa
=> exchange schedule is now previewed when hovering through class options

src/components/exchange/requests/issue/cards/CreateRequestCard.tsx
- The exchange schedule updated request origin classes each time a new course was added based on the previously selected destination option. That is now fixed.
=> fixed origin class update bug

src/components/exchange/requests/issue/ChooseIncludedCourseUnits.tsx, src/components/exchange/requests/issue/CreateRequest.tsx, src/components/exchange/requests/issue/CustomizeRequest.tsx, src/components/exchange/requests/issue/cards/CreateRequestCard.tsx
=> fix: schedule preview auto fill

src/components/exchange/requests/view/cards/ListRequestChanges.tsx
=> Changed request exchange to table

src/components/planner/Schedule.tsx
=> Loading spinner while fetching schedule information

.env.example, src/utils/index.ts
Closes #416 
When testing, don't forget to set `VITE_APP_T_CLASS_CONFLICTS` in your `.env` file.
=> Enable conflicts with T classes

src/components/admin/requests/AdminSendEmail.tsx, src/components/admin/requests/cards/AdminRequestCardFooter.tsx, src/utils/mail.ts
=> Fix: add newlines in mailto body

src/@types/index.d.ts, src/components/admin/requests/cards/AdminRequestCardFooter.tsx, src/components/admin/requests/cards/MultipleStudentExchangeCard.tsx, src/components/admin/requests/cards/PersonExchanges.tsx, src/components/admin/requests/cards/SingleStudentExchangeCard.tsx, src/components/admin/requests/cards/StudentEnrollmentCard.tsx, src/components/admin/requests/cards/TreatExchangeButton.tsx, src/hooks/admin/useStudentCourseMetadata.tsx
Tratar button on admin was with wrong course id and not present in enrollments
=> fix: tratar exchange button

src/components/admin/AdminMainContent.tsx, src/components/admin/AdminPagination.tsx, src/components/admin/requests/MultipleStudentExchanges.tsx, src/components/admin/requests/SingleStudentExchanges.tsx, src/components/admin/requests/StudentEnrollments.tsx, src/contexts/admin/AdminPaginationContext.tsx, src/hooks/admin/useMultipleStudentExchanges.tsx, src/hooks/admin/useSingleStudentExchanges.tsx, src/hooks/admin/useStudentEnrollments.tsx
Admin pagination was naive and showed infinite pages even though the results were the exact same
=> fix: admin pagination show correct total pages

src/api/services/exchangeRequestService.ts, src/components/exchange/requests/issue/CustomizeRequest.tsx
Toast messages after submitting request are confusing.
=> feat: improve toast messages (small change)

src/@types/index.d.ts, src/components/admin/requests/cards/SingleStudentExchangeCard.tsx, src/components/exchange/requests/view/cards/MineRequestCard.tsx
> [Backend pull request associated](https://github.com/NIAEFEUP/tts-be/pull/223)
=> Show Sent Urgent Requests [frontend]

src/components/exchange/requests/view/ViewRequests.tsx, src/components/exchange/requests/view/ViewRequestsFilters.tsx
Basically add a select to filter requests by state
=> added filter logic

src/components/planner/Schedule.tsx, src/components/planner/schedule/PrintSchedule.tsx
Now the png does not keep the buttons, has extra padding and correct file name.
=> Enhance schedule to image
