NIAEFEUP/tts-fe

src/AppTheme.js
src/components/CardFeature.jsx
src/components/Header.jsx
src/components/Hero.jsx
src/components/Profile/OptionRow.jsx
src/components/Profile/ProfileCard.jsx
src/style.js

The website default colors were changed. 
The grid component, however, remained as it was, since it was modified in another pull request. 
closes #14

Theme color

---

src/App.tsx
src/pages/NotFound.tsx

The page appears when the address is incorrect, as intended, its design is very simple, however.
The page consists of two lines of text, a bigger one with the text "404" and a smaller with the text "PAGE NOT FOUND", and a button beneath them with the text "Go to Planner" that redirects to the "/" route.
Desktop:
Mobile:

8 not found page 404

---

src/components/planner/OptionsController.tsx
src/components/planner/ScheduleListbox.tsx
src/components/planner/ShareButtons.tsx

- After importing a schedule, the "LastSelected" of the preview feature is set to the imported schedule
- After importing a schedule, the changes done to it are now permanent
- Removed the "BadState" error from the ScheduleListBox
- LastSelected called for all imported schedule options
- ScheduleListBox.tsx now has the logic to re-save the multipleOptions.selected schedule to the multipleOptions.options
- OnClick functions are now called by arrow functions in ScheduleListBox.tsx
Consistency of the website
No
No
- Chromium

126 hotfix import export

---

src/components/planner/ShareButtons.tsx
src/styles/schedule.css

Closes #127 
Added a border to the link's input box, removed the default outline when focusing the input box and changed the DocumentDuplicateIcon size to match the new size of the input box (I can try to keep it with the same size and align its center with the input box's center). I also changed the background of the input box while on dark mode although it wasn't the plan. There are videos below with the design I went for and different variations I tried before reaching the final design. I'd like to know what you like/dislike about what I implemented and if you prefer any of the other options or other combinations.
[implemented.webm](https://user-images.githubusercontent.com/96185733/220778111-d010dc9c-2648-439e-9277-ec2bd548ba5a.webm) …

127-importexport-update-input-box-borders

---

docker-compose.yaml

While trying to run docker-compose build, i was receiving an error message because there was some troubles with a few lines at docker-compose.yaml. After removing them, everything is fine and i can run docker without giving me any error messages. If  everything seems fine for you, i think it would be better to remove this lines.

Removed tts-bridge on docker-compose.yaml

---

src/components/planner/MoreActionsButton.tsx

Fix export to csv

---

src/components/planner/Schedule.tsx
src/components/planner/sidebar/SelectedOptionController.tsx
src/components/planner/sidebar/selectedOptionController/PasteOption.tsx

Firefox doesn't support Clipboard API readText method, so this PR adds an alternative way of pasting an option opening a text input to paste the option, which doesn't depend on clipboard API, for browsers not supporting the method.
Demo:
https://github.com/NIAEFEUP/tts-revamp-fe/assets/53405284/b8d0e893-92a0-4a17-a525-d127032da976

No support Clipboard API readText method alternative

---

src/components/planner/sidebar/ClassSelector.tsx
src/components/planner/sidebar/CoursesController.tsx
src/components/planner/sidebar/ScheduleListbox.tsx
src/components/ui/button.tsx
src/components/ui/dropdown-menu.tsx
src/utils/utils.ts

New dropdown for class selection.

---

src/components/planner/Schedule.tsx
src/components/planner/Sidebar.tsx
src/components/planner/schedules/ResponsiveLessonBox.tsx
src/components/planner/sidebar/OptionsController.tsx
src/pages/TimeTableScheduler.tsx

Closes #149 
For a smaller screen, the schedule and sidebar design changes. When the page is small, the schedule emphasizes the course and more important information and the schedule card goes to the end of the page.

Reorganize schedule selector in mobile mode

---

src/App.tsx
src/api/backend.ts
src/api/storage.ts
src/components/planner/Schedule.tsx
src/components/planner/Sidebar.tsx
src/components/planner/schedules/ClassBox.tsx
src/components/planner/schedules/LessonBox.tsx
src/components/planner/sidebar/OptionsController.tsx
src/components/planner/sidebar/SelectedOptionController.tsx
src/components/planner/sidebar/selectedOptionController/PasteOption.tsx
src/components/planner/sidebar/selectedOptionController/fillOptions.ts
src/components/planner/sidebar/sessionController/CoursePicker.tsx
src/components/planner/sidebar/sessionController/CsvExport.tsx
src/components/planner/sidebar/sessionController/Export.tsx
src/contexts/CombinedProvider.tsx
src/contexts/MultipleOptionsContext.tsx
src/pages/TimeTableScheduler.tsx
src/utils/index.ts

Closes #222 
This PR removes all usages of optionsList and uses multipleOptions instead.

Unify multipleOptions and optionsList

---

src/components/planner/sidebar/CoursesController/ClassSelector.tsx

We had a problem where sometimes when we selected a class and then switched to another option (clicked on another emoji) and returned back to our previous emoji, sometimes the class name was not appearing on the dropdown.
This was because the `preview` which determines if we are previewing or not a class schedule was not correctly being set to `null` when a class is selected.

FIX: preview not null when class selected

---

src/api/backend.ts
src/config/local.json
src/config/prod.json

As the same thing that was done on this [scrapper pr](https://github.com/NIAEFEUP/uporto-schedule-scrapper/pull/116), the year should not be static and instead dynamic.
This way we don't need to touch it while in deployment to alter the configuration file for the year

Course api year is now dynamic

---

src/components/planner/sidebar/sessionController/CoursePicker.tsx

I noticed that the picked courses were disappearing when we refreshed the page. 
It is now fixed with this PR, it was some weird bug related to promises again.

FIX: picked courses are now being correctly stored

---

src/components/planner/sidebar/sessionController/course-picker/MajorSearchCombobox.tsx

There was a bug when I clear the storage and refreshing the page: I select the search major modal and start typing before it fetched the majors. It would break the app by calling some method on undefined. This way, the it returns before making something with the value.
I also have added the faculty to the option name, and refactoring some code.

Fix search major bug

---

src/components/planner/Schedule.tsx
src/components/planner/schedules/ClassBox.tsx
src/components/planner/sidebar/SelectedOptionController.tsx

When we would put the window side by side with another window, the schedule would just disappear.
As it was before the refactor

FIX: <Schedule> now appearing on smaller screens

---

.github/workflows/niployments.yaml

When we separated the secrets per environment depending on the branch, we didn't add correctly adapt the action workflow.
This PR takes care of that.

fix: make deploy action use branch environment

---

src/components/planner/sidebar/CoursesController/ClassSelector.tsx

Closes #267 
When we are previewing a schedule of a class and we press the `ESC` key in order to make the modal disappear, prior to this PR the class that would remain would be the previewed one and not the original one.

fix: schedule preview is restored on esc

---

src/App.tsx
src/config/local.json
src/config/prod.json

Closes #271 
Currently, on our website (tts.niaefeup.pt), all links have the /tts/ prefix, which is a tombstone due to the previously used urll (ni.fe.up.pt/tts).
So, the goal is to have for example tts.niaefeup.pt/planner instead of tts.niaefeup.pt/tts/planner.
This can be used by changing the .json config.
This PR also changes the way we access it on the localhost, it will be `localhost:3100/` always from now on instead of the verbosity of `localhost:3100/tts`

chore: remove tts prefix in production

---

src/components/planner/sidebar/CoursesController.tsx
src/components/planner/sidebar/CoursesController/ClassSelector.tsx
src/components/planner/sidebar/CoursesController/ClassSelectorDropdownController.tsx

Besides changing the UI for the mobile and smaller devices, this PR also simplifies the rendering logic of `ClassSelector`, creating a new file.

feat: mobile professor dropdown menu is responsive

---

src/components/planner/sidebar/selectedOptionController/CopyOption.tsx
src/components/planner/sidebar/selectedOptionController/PasteOption.tsx

Closes #274 
The hash was accumulating the `''` for some reason, so the paste option was pasting ghost course units and it was broken. This PR fixes it.

fix: pasting ghost schedule option

---

src/components/planner/Schedule.tsx

As @jose-carlos-sousa noticed, if the slots were of the same day they weren't being sorted correctly as we weren't having the start time of the slots into account.
This PR fixes it.

fix: slot order logic now takes into account start time if days are the same

---

src/components/faqs/PlannerFaqs.tsx
src/components/planner/schedule/PrintSchedule.tsx
src/components/planner/schedule/ToggleScheduleGrid.tsx
src/components/planner/sidebar/CoursesController/ClassSelector.tsx
src/components/planner/sidebar/OptionsController.tsx
src/components/planner/sidebar/SelectedOptionController.tsx
src/components/planner/sidebar/selectedOptionController/CopyOption.tsx
src/components/planner/sidebar/selectedOptionController/PasteOption.tsx
src/components/planner/sidebar/selectedOptionController/RandomFill.tsx
src/components/planner/sidebar/sessionController/CsvExport.tsx
src/components/planner/sidebar/sessionController/course-picker/MajorSearchCombobox.tsx
src/utils/AnalyticsTracker.ts

Closes #262 
Features trackable:
- Copy Schedule
- Paste Schedule
- Random Fill
- Options Order Changed
- Option Renamed
- Schedule Emoji Changed
- Screenshot
- Grid View Toggle
- Export to CSV
- Class Lock Toggled
And all the faqs question, when opened

Setup features and faq analytics

---

src/components/planner/sidebar/CoursesController/ClassItem.tsx
src/utils/index.ts

This bug happens when the class_id that comes from the backend changes. The multipleOptions still has the old picked_class_id, but there's no longer any class in the courses inside pickedCourses with the id that's in the picked_class_id, so what I've underlined is undefined and it's a mess.
Adding that if (pickedClass) on the last line (which isn't in the main, I added it locally to test the problem) stops the problem. The multiple options are not putting the picked_class_id associated with the course that was changed when that class ceased to exist.

fix: app crashing sometimes after refresh course unit hashes

---

src/api/storage.ts
src/components/planner/sidebar/CoursesController/ClassSelector.tsx
src/components/planner/sidebar/CoursesController/ClassSelectorDropdownController.tsx
src/utils/index.ts

Closes #303 
Besides this bug being solved, the filters are now stored on local storage so when the user refreshes or comes back to the page, the teacher filters will stay put.

fix: filtered teachers remain put

---

src/components/planner/schedules/SlotBoxes.tsx
src/components/planner/sidebar/sessionController/CollabModal.tsx
src/components/planner/sidebar/sessionController/CollabSessionModal.tsx

There was a modal called `<CollabSession>` and also a `index.ts` type named `CollabSession` and this was giving problems which was introduced in my pr about setting up a linter

fix: collab session duplicate definition

---

src/components/planner/sidebar/CoursesController/ClassSelector.tsx
src/components/planner/sidebar/CoursesController/ClassSelectorDropdownController.tsx

Closes #300 
Apparently the `Dropdown` component we are using acts in weird ways. 
Even though the dropdown was closed, for some reason, during a small amount of time, the `<ClassItem>`s that have the `onMouseEnter` are activated, even though they are no longer visible.
The fix was putting an `if` statement inside the `onMouseEnter` event listener function so that the preview is only added when the dropdown is actually open.

fix: class selection now always sets the correct class on the schedule

---

src/styles/schedule.css

Closes #313 
Conflicts between TPs (red) are shown above warnings between T and TPs (yellow).

fix: class conflict between T and two TPs

---

src/components/planner/sidebar/CoursesController/ClassSelector.tsx

Closes #314
Locks are not available if the selection is empty.

fix: lock option

---

src/components/planner/sidebar/CoursesController/ClassItem.tsx
src/components/planner/sidebar/CoursesController/ClassSelectorDropdownController.tsx
src/utils/index.ts

It changes the logic inside `ClassItem` so that in cases like the one described in #313 the triangle shows red instead of yellow.

fix: class item conflict indicator correct severity

---

package-lock.json
package.json
src/api/socket.ts

Closes #233 
This PR sets up Socket.IO in the frontend and creates a wrapper class to more effortlessly use the WebSocket communication.
To test this, run the backend on the `feature/websockets` branch add the following to `index.tsx`
```js
import { sessionsSocket } from './api/socket'
// ...
sessionsSocket.connect()
sessionsSocket.on('response', data => {
console.log(data);
});
// Send message to server
function sendMessage(message) {
sessionsSocket.emit('test', message);
};
sessionsSocket.on('connect', () => {
sendMessage('message');
});
setTimeout(() => {
sessionsSocket.disconnect();
}, 1000);
```

Add WebSocket integration

---

src/components/planner/sidebar/CoursesController.tsx

Added a button that erases all selected classes in the current option.
Design is based on the button from the CoursePicker modal.

Allow user to erase classes from option more easily

---

src/components/exchange/requests/view/cards/RequestCard.tsx
src/components/planner/schedules/LessonBox.tsx
src/contexts/CombinedProvider.tsx
src/contexts/ConflictsContext.tsx

Closes #335 
Makes the button disabled when Schedule has a severe conflict.

Exchange not allowing submission when Schedule has a conflict

---

.github/workflows/sentry.yaml

As per the suggestion in the error message from the sentry action

fix: sentry action could not find version

---

src/api/backend.ts

Adding a slash to the end of the login and logout urls solve the issue we are having in tts-staging.niaefeup.pt of the fact that clicking on the button or in the login icon does not correctly redirect to the backend.

fix: invalid url to sso login

---

package-lock.json
package.json
src/@types/index.d.ts
src/api/socket.ts
src/components/planner/sidebar/sessionController/CollabModal.tsx
src/components/planner/sidebar/sessionController/CollabPickSession.tsx
src/components/planner/sidebar/sessionController/CollabSessionModal.tsx
src/components/planner/sidebar/sessionController/CollaborativeSession.tsx
src/contexts/CollabSessionContext.tsx
src/hooks/useCollabSessions.ts
src/hooks/useDarkMode.tsx
src/hooks/useLocalStorage.ts
src/index.tsx
src/utils/human-time.ts

This pull request is closely related to [backend pull request #122](https://github.com/NIAEFEUP/tts-be/pull/122).  
- Supports multiple collaboration sessions using SocketIO rooms, they are saved in the database and can be accessed again if they haven't expired
- One user creates the session and can then share the access link with others
- Usernames are taken from authenticated users, or, as a fallback, randomly generated with an AdjectiveAnimal combination (but can be changed later)
- Username information is shared in the session as an example of real-time updates
- For testing purposes, ping messages are broadcast in the room (can be seen in browser console)

Collaborative Sessions - Actually create a session [Frontend]

---

src/components/admin/requests/AdminSendEmail.tsx
src/components/admin/requests/cards/AdminRequestCardFooter.tsx
src/components/admin/requests/cards/MultipleStudentExchangeCard.tsx
src/components/admin/requests/cards/SingleStudentExchangeCard.tsx
src/components/admin/requests/cards/StudentEnrollmentCard.tsx
src/utils/mail.ts

Custom mailto for exchanges and enrollments

---

src/components/exchange/requests/issue/PreviewRequestForm.tsx

There should be no doubt left that urgent requests are not for everyone and should be used carefully

fix: make urgent request text more clear

---

src/utils/error.ts

Instead of "tens conflitos", it now says "alguém na troca", because we may not have conflicts but other people may do

fix: better conflict text to indicate conflicts may not happen with us

---

src/components/exchange/requests/issue/PreviewRequestForm.tsx

The tooltip is buggy and shows every time we submit the form, so we need another way to put a text saying there are conflicts.
However, this is not crucial because conflicts are shown on the left and when the backend answers with a message

fix: remove faulty submit tooltip

---

src/api/services/exchangeRequestService.ts

jwt with dots is messing up the nginx in the production build on the frontend

fix: base64 jwt decode in url

---

src/components/exchange/schedule/ExchangeSchedule.tsx
src/components/planner/schedule/PlannerSchedule.tsx
src/components/planner/schedules/LessonBox.tsx
src/components/planner/sidebar/CoursesController/ClassItem.tsx
src/contexts/CombinedProvider.tsx
src/contexts/ConflictsContext.tsx
src/utils/index.ts

Fixes an weird (and not so surprising) behavior, where setting `VITE_APP_T_CLASS_CONFLICTS=1` will result in conflicts with theoretical classes appearing in red in the normal planner. This still need to be discussed, as it complicates unnecessarily the logic for a somewhat unreasonable requirement from the course's board.
To test this PR, do not forget to set `VITE_APP_T_CLASS_CONFLICTS=1` in your `.env` file.

Fix T-class conflicts on normal planner
